#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:demo
#    driver-class-name: org.h2.Driver

#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://admin:admin@aws-cluster-eqzbn.mongodb.net/spring-mongodb?retryWrites=true&w=majority

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
#    username: root
#    password: rootroot
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect

spring:
  output:
    ansi:
      enabled: ALWAYS


  datasource:
    url: jdbc:mysql://${spring.datasource.name}${spring.datasource.endpoint}:${spring.datasource.port}/${spring.datasource.name}
    name: spring
    port: 3306

    endpoint: .c8nq4mxqkhfb.us-east-2.rds.amazonaws.com
    username: admin
    password: adminadmin

#    endpoint: localhost
#    username: root
#    password: rootroot

#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect



